apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql-master
  template:
    metadata:
      labels:
        app: postgresql-master
    spec:
      containers:
        - name: postgresql-master
          image: bitnami/postgresql
          ports:
            - containerPort: 5432
          # volumeMounts:
          #   - name: postgresql-master-data
          #     mountPath: /bitnami/postgresql
          env:
            - name: POSTGRESQL_PGAUDIT_LOG
              value: "READ,WRITE"
            - name: POSTGRESQL_LOG_HOSTNAME
              value: "true"
            - name: POSTGRESQL_REPLICATION_MODE
              value: "master"
            - name: POSTGRESQL_REPLICATION_USER
              value: "repl_user"
            - name: POSTGRESQL_REPLICATION_PASSWORD
              value: "repl_password"
            - name: POSTGRESQL_USERNAME
              value: "postgres"
            - name: POSTGRESQL_PASSWORD
              value: "bananas"
            - name: POSTGRESQL_DATABASE
              value: "db"
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
      # volumes:
      # - name: postgresql-master-data
      #   hostPath:
      #       path: /mnt/postgresql-master-data
      #       type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-master
spec:
  selector:
    app: postgresql-master
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
